channels:
  - conda-forge
dependencies:
  - python=3.12
  # docs' requirements
  - sphinx
  - nbsphinx
  - pandoc
  - sphinx-book-theme
  - sphinx-copybutton
  - myst-parser
  - sphinx-remove-toctrees
  # from pyproject.toml
  - xarray>=2023.11.0
  - healpy
  - sparse
  - opt_einsum
  - numba
  - numpy
  - sparse
  - scikit-learn
  - opt_einsum
  - cdshealpix
  - astropy
  - pip
  - pip:
      - nbsphinx_link>=1.3.1
      - -e ../.
